### ISSUE TITLE
Refresh Token is gone TT in swagger

### ISSUE THREAD

**Issue by TikhampornSky** [TendonT52/soft-arch-proj#31]
I didn't see refresh_token in log-in response
<img width="1324" alt="Screenshot 2566-09-28 at 22 54 31" src="https://github.com/TendonT52/soft-arch-proj/assets/88883551/cf9996ae-6313-43ed-89f8-fdae901a98c8">

Result in Postman
<img width="1068" alt="Screenshot 2566-09-28 at 22 55 12" src="https://github.com/TendonT52/soft-arch-proj/assets/88883551/b99b8898-8b75-4f4e-82b1-f979673be165">

**Comment by TendonT52** [comment]
The refresh token is stored in a cookie, which is why it is not in the body response.

**Comment by TikhampornSky** [comment]
Still Not found in browswer
![Uploading Screenshot 2566-10-07 at 11.05.42.png…]()

**Comment by TikhampornSky** [comment]
Appear in `Network` Tab
