### ISSUE TITLE
Staus Doesn't Match

### ISSUE THREAD

**Issue by TikhampornSky** [TendonT52/soft-arch-proj#32]
> จากที่สังเกตมา น่าจะเป็นที่ Mrthod Get, Delete

**Get Student Me**
<img width="1392" alt="Screenshot 2566-09-29 at 08 55 20" src="https://github.com/TendonT52/soft-arch-proj/assets/88883551/07db0298-6332-44e3-8319-a5fe9804b100">
Got 400, but it should be 200

**Get Student By ID**
<img width="1396" alt="Screenshot 2566-09-29 at 08 56 04" src="https://github.com/TendonT52/soft-arch-proj/assets/88883551/0ec9c6ef-05e9-482c-ad73-59f837b11a95">
Got 400, but it should be 200

**Get All company**
<img width="1426" alt="Screenshot 2566-09-29 at 09 13 19" src="https://github.com/TendonT52/soft-arch-proj/assets/88883551/dd5bb3a4-3a11-4f72-9c27-0abec20b0e55">

**Get Approved Company**
<img width="1396" alt="Screenshot 2566-09-29 at 09 14 03" src="https://github.com/TendonT52/soft-arch-proj/assets/88883551/f2c6c260-9425-4c5e-b29a-1646909b8aa9">

**Get Company Me**
<img width="1387" alt="Screenshot 2566-09-29 at 09 14 35" src="https://github.com/TendonT52/soft-arch-proj/assets/88883551/47ec9086-af0c-445a-b0a3-2fea7f40ac4d">

**Get Company By ID**
<img width="1410" alt="Screenshot 2566-09-29 at 09 15 07" src="https://github.com/TendonT52/soft-arch-proj/assets/88883551/8a3d2c6f-5fd7-415e-a621-0a77f020544c">

**Get Post By ID**
<img width="1404" alt="Screenshot 2566-09-29 at 09 19 09" src="https://github.com/TendonT52/soft-arch-proj/assets/88883551/656a02e8-2716-4418-8bac-77074dca1056">

**Get All Posts (Search)**
<img width="1404" alt="Screenshot 2566-09-29 at 09 21 09" src="https://github.com/TendonT52/soft-arch-proj/assets/88883551/a355e6c6-5c14-43a3-a891-748887cd6394">

**Get Benefits, Open Positions, Skills**
<img width="371" alt="Screenshot 2566-09-29 at 09 29 12" src="https://github.com/TendonT52/soft-arch-proj/assets/88883551/d97cd398-237e-40f7-bcce-e18b4ed3a6b9">
<img width="390" alt="Screenshot 2566-09-29 at 09 29 19" src="https://github.com/TendonT52/soft-arch-proj/assets/88883551/fbf4e5a3-1891-40b9-8cfc-178e1b71acca">

**Delete Post**
<img width="1404" alt="Screenshot 2566-09-29 at 09 34 38" src="https://github.com/TendonT52/soft-arch-proj/assets/88883551/aa4fbb40-3e22-4f14-a75b-40a0689f7ebc">

**Get Reports**
<img width="1426" alt="Screenshot 2566-09-29 at 09 38 18" src="https://github.com/TendonT52/soft-arch-proj/assets/88883551/fe77a1b7-3ac0-4356-b3d3-b7f424275031">

**Get Report**
<img width="1418" alt="Screenshot 2566-09-29 at 09 39 05" src="https://github.com/TendonT52/soft-arch-proj/assets/88883551/2a4caa2b-7e2a-4011-8c70-8ae549e27669">

**Comment by TendonT52** [comment]
I cannot reproduce this issue. Maybe you should try it on the latest API gateway. 

If you still have the issue, please provide me with the steps to reproduce it.

**Comment by TikhampornSky** [comment]
Still have problem
1. Sign Up Student
`{
  "name": "Tikhamporn Tepsut",
  "email": "6330203521@student.chula.ac.th",
  "password": "123456",
  "passwordConfirm": "123456",
  "description": "I am com Eng!",
  "faculty": "Engineer",
  "major": "Cimputer",
  "year": 4
}`
2. Login as Student
3. Get Student Me
