### ISSUE TITLE
Int64 in gRPC

### ISSUE THREAD

**Issue by TikhampornSky** [TendonT52/soft-arch-proj#33]
The actual type of `id` is init64, but in swagger it shows its type was string
<img width="1406" alt="Screenshot 2566-09-29 at 08 58 14" src="https://github.com/TendonT52/soft-arch-proj/assets/88883551/2ab6dac2-4346-4508-9833-f902268431e3">

**แต่ถ้าไม่แก้ ก็กดส่งได้ปกตินะ

**Comment by TendonT52** [comment]
int64 in proto is mapping to string in go
int32 in proto is mapping to int in go
